#Application Configuration
server:
  port: 8094
  error:
    include-message: always
    include-binding-errors: always

spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    #url: jdbc:mysql://uhsgyi16cmvcpj9d:ExLvdOGZBK7SWhLs68Co@bmj3ll0yjatblf6htcsg-mysql.services.clever-cloud.com:3306/bmj3ll0yjatblf6htcsg?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mysql://localhost:3306/cargoservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    basic:
      enabled: false
  #boot:
  #  admin:
  #    client:
  #      url: http://localhost:8086
eureka:
  client:
    serviceUrl:
      #defaultZone: https://ts-registryservices.azurewebsites.net/eureka/
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /ts-api-docs
  swagger-ui:
    path: /index.html