#Application Configuration
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /console
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://ujfd9pxu3n1tuiyz:yF9Vc6vOsLAFUX7VU2oM@bblegg6rlljajspuirxg-mysql.services.clever-cloud.com:3306/bblegg6rlljajspuirxg?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    #url: jdbc:mysql://localhost:3306/customerservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    basic:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: https://registryservice18.azurewebsites.net/eureka/
      #defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
