#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
      path: /console
  # ===============================
  # DB
  # ===============================
  datasource:
    #url: jdbc:mysql://uz6adiifrbv0de9t:Qd3BhXRCqfGXdGZnGrPJ@batyrohtpor88xl6scsm-mysql.services.clever-cloud.com:3306/batyrohtpor88xl6scsm?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mysql://localhost:3306/driverservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    basic:
      enabled: false
eureka:
  client:
    serviceUrl:
      #defaultZone: https://ts-registryservices.azurewebsites.net/eureka/
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
springdoc:
  api-docs:
    path: /ts-api-docs
  swagger-ui:
    path: /index.html