server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  security:
      basic:
        enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cargo-service
          uri: lb://cargoservice
          predicates:
            - Path=/cargoservice/**
        - id: config-service
          uri: lb://configservice
          predicates:
            - Path=/configservice/**
        - id: customer-service
          uri: lb://customerservice
          predicates:
            - Path=/customerservice/**
        - id: driver-service
          uri: lb://driverservice
          predicates:
            - Path=/driverservice/**
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/userservice/**