server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  security:
      basic:
        enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cargo-service
          uri: lb://cargo-service
          predicates:
            - Path=api/cargoservice/**
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=api/configservice/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=api/customerservice/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=api/driverservice/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=api/userservice/**

management:
  endpoints:
    web:
      exposure:
        include: "*"            