server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  security:
      basic:
        enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cargo-service
          uri: lb://cargo-service
          predicates:
            - Path=/cargoservice/**
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/configservice/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customerservice/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/driverservice/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/userservice/**