server:
  port: 8087
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: example-service
  boot:
    admin:
      client:
        url: http://localhost:8086

management:
  endpoints:
    web:
      exposure:
        include: "*"

